/**
 * Auto-generated from design tokens
 * Do not edit manually
 */
export const tokens = {
  colors: {},
  base: {
    color: {
      'gray-50': 'var(--color-gray-50)',
      'gray-100': 'var(--color-gray-100)',
      'gray-200': 'var(--color-gray-200)',
      'gray-300': 'var(--color-gray-300)',
      'gray-400': 'var(--color-gray-400)',
      'gray-500': 'var(--color-gray-500)',
      'gray-600': 'var(--color-gray-600)',
      'gray-700': 'var(--color-gray-700)',
      'gray-800': 'var(--color-gray-800)',
      'gray-900': 'var(--color-gray-900)',
      'gray-950': 'var(--color-gray-950)',
      'pink-50': 'var(--color-pink-50)',
      'pink-100': 'var(--color-pink-100)',
      'pink-150': 'var(--color-pink-150)',
      'red-50': 'var(--color-red-50)',
      'red-100': 'var(--color-red-100)',
      'red-200': 'var(--color-red-200)',
      'red-300': 'var(--color-red-300)',
      'red-400': 'var(--color-red-400)',
      'red-500': 'var(--color-red-500)',
      'red-600': 'var(--color-red-600)',
      'blue-50': 'var(--color-blue-50)',
      'blue-100': 'var(--color-blue-100)',
      'blue-500': 'var(--color-blue-500)',
      'blue-600': 'var(--color-blue-600)',
      white: 'var(--color-white)',
      black: 'var(--color-black)',
      background: 'var(--color-background)',
      foreground: 'var(--color-foreground)',
      muted: 'var(--color-muted)',
      mutedForeground: 'var(--color-muted-foreground)',
      border: 'var(--color-border)',
      primary: 'var(--color-primary)',
      primaryForeground: 'var(--color-primary-foreground)',
      secondary: 'var(--color-secondary)',
      secondaryForeground: 'var(--color-secondary-foreground)',
      accent: 'var(--color-accent)',
      accentForeground: 'var(--color-accent-foreground)',
      destructive: 'var(--color-destructive)',
      destructiveForeground: 'var(--color-destructive-foreground)',
      'content-primary': 'var(--color-content-primary)',
      'content-secondary': 'var(--color-content-secondary)',
      'content-disabled': 'var(--color-content-disabled)',
      'content-action': 'var(--color-content-action)',
      'content-danger': 'var(--color-content-danger)',
      'status-error': 'var(--color-status-error)',
      'status-warning': 'var(--color-status-warning)',
      'status-success': 'var(--color-status-success)',
      'status-info': 'var(--color-status-info)',
    },
    shadow: {
      none: 'var(--shadow-none)',
      sm: 'var(--shadow-sm)',
      md: 'var(--shadow-md)',
      lg: 'var(--shadow-lg)',
      xl: 'var(--shadow-xl)',
      button: 'var(--shadow-button)',
      buttonHover: 'var(--shadow-button-hover)',
      input: 'var(--shadow-input)',
    },
    spacing: {
      '0': 'var(--spacing-0)',
      '1': 'var(--spacing-1)',
      '2': 'var(--spacing-2)',
      '3': 'var(--spacing-3)',
      '4': 'var(--spacing-4)',
      '5': 'var(--spacing-5)',
      '6': 'var(--spacing-6)',
      '8': 'var(--spacing-8)',
      '10': 'var(--spacing-10)',
      '12': 'var(--spacing-12)',
      '16': 'var(--spacing-16)',
      '20': 'var(--spacing-20)',
      '24': 'var(--spacing-24)',
      '32': 'var(--spacing-32)',
      '40': 'var(--spacing-40)',
      '48': 'var(--spacing-48)',
      '64': 'var(--spacing-64)',
    },
    font: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
    },
    fontSize: {
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
    },
    lineHeight: {
      none: 'var(--line-height-none)',
      tight: 'var(--line-height-tight)',
      snug: 'var(--line-height-snug)',
      normal: 'var(--line-height-normal)',
      relaxed: 'var(--line-height-relaxed)',
    },
    fontWeight: {
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
    },
  },
} as const;

export type ThemeTokens = typeof tokens;
