name: Deploy dist to server
description: deploy dist to server
inputs:
  source:
    description: source path
    required: true
  package:
    description: package name
    required: true
  msg:
    description: messages send to channel
    required: false

runs:
  using: "composite"
  steps:
    - name: Build Packages
      run: pnpm turbo run build --filter ${{ inputs.package }}
      shell: bash
    - name: send files to server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ env.SERVER_SSH_KEY }}
        SOURCE: ${{ inputs.source }}
        REMOTE_HOST: ${{ env.REMOTE_HOST }}
        REMOTE_USER: ${{ env.REMOTE_USER }}
        TARGET: ${{ env.REMOTE_TARGET }}
        EXCLUDE: "/dist/, /node_modules/"
    - name: send telegram message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ env.TELEGRAM_CHANNEL_ID }}
        token: ${{ env.TELEGRAM_BOT_TOKEN }}
        message: ${{ inputs.msg }}
