name: changesets handler
description: A wrapper action with friendly outputs based on changesets/action@v1
outputs:
  createPrOnly:
    description: "changesets/action create pr only without packages published"
    value: ${{ steps.changesets.outputs.published == 'false' && steps.changesets.outputs.hasChangesets == 'true' }}
  shouldDeploySite:
    description: "changesets/action published packages and include @bbki.ng/site"
    value: ${{ steps.changesets.outputs.published == 'true' && (contains(fromJson(steps.changesets.outputs.publishedPackages).*.title, '@bbki.ng/site')) }}
  shouldDeployManual:
    description: "changesets/action published packages and include @bbki.ng/manual"
    value: ${{ steps.changesets.outputs.published == 'true' && (contains(fromJson(steps.changesets.outputs.publishedPackages).*.title, '@bbki.ng/manual')) }}
runs:
  using: "composite"
  steps:
    - name: Create Release Pull Request or Publish to npm
      id: changesets
      uses: changesets/action@v1
      with:
        # Skip publishing - only create version PRs until NPM_TOKEN is renewed
        version: pnpm changeset version
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
