name: Auto Release

on:
  push:
    branches:
      - autorelease

jobs:
  merge-pr:
    name: Merge Release Pr
    runs-on: ubuntu-latest
    steps:
      - id: merge-changes
        name: merge changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const res = await github.rest.pulls.create({
              owner: 'bbbottle',
              repo: 'bottle',
              head: 'bbbottle:autorelease',
              base: 'main',
              title: 'new release content',
            });

            const { number } = res.data;

            github.rest.pulls.merge({
              owner: 'bbbottle',
              repo: 'bottle',
              pull_number: number,
            });
