name: Deploy
on:
  workflow_run:
    workflows:
      - "Release"
    branches:
      - main
    types:
      - completed
jobs:
  builds:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'changeset-release')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x

      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build packages
        run: pnpm turbo run build
      - name: Deploy bbki.ng to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_SITE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
