name: Deploy dist to server
on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      msg:
        type: string
        required: false
    secrets:
      SERVER_SSH_KEY:
        required: true
      REMOTE_HOST:
        required: true
      REMOTE_USER:
        required: true
      REMOTE_TARGET:
        required: true
      TELEGRAM_CHANNEL_ID:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build Packages
        run: pnpm turbo run build --filter ${{ inputs.package }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: send files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: "packages/site/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ inputs.msg }}
