name: Deploy dist to server
on:
  workflow_call:
    inputs:
      package:
        type: string
        required: true
      msg:
        type: string
        required: false
    secrets:
      serverPrivateKey:
        required: true
      remoteHost:
        required: true
      remoteUser:
        required: true
      target:
        required: true
      msgChannelId:
        required: true
      botToken:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js 17.x
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install Dependencies
        run: pnpm install --no-frozen-lockfile
      - name: Build Packages
        run: pnpm turbo run build --filter ${{ inputs.package }}
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: send files to server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.serverPrivateKey }}
          SOURCE: "packages/site/dist/"
          REMOTE_HOST: ${{ secrets.remoteHost }}
          REMOTE_USER: ${{ secrets.remoteUser }}
          TARGET: ${{ secrets.target }}
          EXCLUDE: "/dist/, /node_modules/"
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.msgChannelId}}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: ${{ inputs.msg }}
